version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs/localhost.key:/etc/nginx/certs/localhost.key
      - ./nginx/certs/localhost.crt:/etc/nginx/certs/localhost.crt
      - ./nginx/swagger-ui:/usr/share/nginx/html/swagger-ui

  jobly-sqlserver:
    container_name: jobly-sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "LZpb8R9Ozsrab6Vaez6L2oNsP1z79o2v"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433

  jobly-postgres_primary:
    container_name: jobly-postgres_primary
    image: postgres:14-alpine
    user: postgres
    healthcheck:
      test: 'pg_isready -U user --dbname=postgres'
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 md5"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    command: |
      postgres 
      -c wal_level=replica 
      -c hot_standby=on 
      -c max_wal_senders=10 
      -c max_replication_slots=10 
      -c hot_standby_feedback=on
    volumes:
      - ./00_init.sql:/docker-entrypoint-initdb.d/00_init.sql

  jobly-postgres_replica:
    container_name: jobly-postgres_replica
    image: postgres:14-alpine
    user: postgres
    healthcheck:
      test: 'pg_isready -U user --dbname=postgres'
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5433:5432
    environment:
      PGUSER: replicator
      PGPASSWORD: password
    command: |
      bash -c "
      if [ ! -f /var/lib/postgresql/data/standby.signal ]; then
        rm -rf /var/lib/postgresql/data/*
        until pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replication_slot --host=jobly-postgres_primary --port=5432
        do
        echo 'Waiting for primary to connect...'
        sleep 1s
        done
        echo 'Backup done, starting replica in standby mode...'
        touch /var/lib/postgresql/data/standby.signal
        chmod 0700 /var/lib/postgresql/data
      fi
      exec postgres"
    depends_on:
      - jobly-postgres_primary

  jobly-mongodb:
    container_name: jobly-mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=admin
    ports:
      - 27017:27017

  jobly-tokens-redis:
    container_name: jobly-tokens-redis
    image: redis:alpine
    ports:
      - 6379:6379

  jobly-vacancies-redis:
    container_name: jobly-vacancies-redis
    image: redis:alpine
    ports:
      - 6380:6379
      
  # jobly-elastic:
  #   container_name: jobly-elastic
  #   image: elasticsearch:8.14.3
  #   environment:
  #     - discovery.type=single-node
  #     - ES_JAVA_OPTS=-Xms512m -Xms512m
  #     - xpack.security.enabled=false
  #     - xpack.security.http.ssl.enabled=false
  #   ports:
  #     - "9200:9200"
 
  # jobly-kibana:
  #   container_name: users-kibana
  #   image: kibana:8.14.3
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://jobly-elastic:9200
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - jobly-elastic
  
  # users-migrations:
  #   container_name: users-migrations
  #   build:
  #     context: ./
  #     dockerfile: ./src/UsersService/UsersService.API/Dockerfile.migrations
  #   environment:
  #     SA_PASSWORD: "LZpb8R9Ozsrab6Vaez6L2oNsP1z79o2v"
  #   depends_on:
  #     - jobly-sqlserver
  #   command: |
  #     sh -c "
  #     until /opt/mssql-tools/bin/sqlcmd -S jobly-sqlserver -U SA -P \"$SA_PASSWORD\" -Q 'SELECT 1' &>/dev/null; do
  #     echo 'Waiting for SQL Server to start...';
  #     sleep 5;
  #     done;
  #     echo 'SQL Server is up - running migrations';
  #     dotnet ef database update -s ./src/UsersService/UsersService.API/UsersService.API.csproj -p ./src/UsersService/UsersService.Infrastructure/UsersService.Infrastructure.csproj;"
