version: "3.8"

services:
  vacancies-postgres_primary:
    container_name: vacancies-postgres_primary
    image: postgres:14-alpine
    user: postgres
    healthcheck:
      test: 'pg_isready -U user --dbname=postgres'
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 md5"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    command: |
      postgres 
      -c wal_level=replica 
      -c hot_standby=on 
      -c max_wal_senders=10 
      -c max_replication_slots=10 
      -c hot_standby_feedback=on
    volumes:
      - ./00_init_vacancies.sql:/docker-entrypoint-initdb.d/00_init_vacancies.sql

  vacancies-postgres_replica:
    container_name: vacancies-postgres_replica
    image: postgres:14-alpine
    user: postgres
    healthcheck:
      test: 'pg_isready -U user --dbname=postgres'
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5433:5432
    environment:
      PGUSER: replicator
      PGPASSWORD: password
    command: |
      bash -c "
      if [ ! -f /var/lib/postgresql/data/standby.signal ]; then
        rm -rf /var/lib/postgresql/data/*
        until pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replication_slot --host=vacancies-postgres_primary --port=5432
        do
        echo 'Waiting for primary to connect...'
        sleep 1s
        done
        echo 'Backup done, starting replica in standby mode...'
        touch /var/lib/postgresql/data/standby.signal
        chmod 0700 /var/lib/postgresql/data
      fi
      exec postgres"
    depends_on:
      - vacancies-postgres_primary

  vacancies-mongodb:
    container_name: vacancies-mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=admin
    ports:
      - 27020:27017