version: "3.8"

services:
  users-sqlserver:
    container_name: users-sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "LZpb8R9Ozsrab6Vaez6L2oNsP1z79o2v"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433

  users-mongodb:
    container_name: users-mongodb
    image: mongodb/mongodb-community-server:latest
    ports:
      - 27017:27017

  users-tokens:
    container_name: users-tokens
    image: redis:alpine
    ports:
      - 6379:6379

  users-elastic:
    container_name: users-elastic
    image: elasticsearch:8.14.3
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xms512m
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    networks:
      - users-service

  users-kibana:
    container_name: users-kibana
    image: kibana:8.14.3
    environment:
      - ELASTICSEARCH_HOSTS=http://users-elastic:9200
    ports:
      - "5601:5601"
    depends_on:
      - users-elastic
    networks:
      - users-service

networks:
  users-service:
    driver: bridge
